### PR TITLE
Leverage o-typography

### PR DESCRIPTION
**Pull request by expe**
- Uses o-typography.
- Mixins `nTypeAlphaSize`, `nTypeAlpha` call the equivalent o-typography mixins
- Next mixins (`nTypeAlphaSize`) have a deprecation warning
- Made demos run with obt; this is so I could test them. If someone could run this through a next app to test, that would be great.

@keirog @matthew-andrews

### CODE REVIEW

**Comment by keirog** [comment]
Would be good to have a readme update but otherwise :+1:  (am happy to do that though)

**Comment by expe** [comment]
Updated the README, let me know if there are any issues. A live table of the variations doesn't currently exist but I imagine we'll add it to the styleguide.

**Comment by i-like-robots** [comment]
I'm actually quite against any further integration of Origami typography into next at the moment because I don't think it quite suits our needs in its current form.

I've quickly bashed out an example of the direction I'd like to see our typography go in [this PR](https://github.com/Financial-Times/next-type/pull/39).

It'd be great to have a discussion about this.

**Comment by AlbertoElias** [comment]
@matthew-andrews @danskinner bringing you guys into the discussion. Should we go for a merge of what @expe has currently done and then work on responsive fonts on top of that, or would it be better to hold off for now?

**Comment by danskinner** [comment]
I'm not yet convinced by the need for responsive fonts but would like to know more. Also not sure why we'd hold off from origami integration. 

Would be good to catch up with everyone concerned today - I don't know enough about the implications of the list above and need to first.

**Comment by matthew-andrews** [comment]
I think we should merge this first … Origami and Next designs **need** to combine otherwise Next and Origami will just undermine each others' goals …

We should continue experiment with responsive fonts **and** listen to and address MattH's concerns separately …

**Comment by AlbertoElias** [comment]
Cool, agreed. Let's do that and have a chat about responsive typography. Is the design meeting with Origami tomorrow at 10am a good time?

**Comment by danskinner** [comment]
I won't be in tomorrow and would like to be there for any discussion.

Let's merge and find another time to talk about the responsive stuff. Today or Friday are good for me.

**Comment by expe** [comment]
I'm free to have a discussion today. @i-like-robots and people from Next free today?

**Comment by i-like-robots** [comment]
Sure

**Comment by i-like-robots** [comment]
I have put together some slides to explain myself because all meetings here should have a Powerpoint presentation. I am not good with business software though so it may lack the pizazz you have come to expect =)

**Comment by expe** [comment]
Going to make a few changes in the o-typography PR at https://github.com/Financial-Times/o-typography/pull/57, will advise when we've merged and made a production release.

**Comment by expe** [comment]
@keirog o-typography 3 has been released so this should be OK to merge. 

The main change was adding guss-typography helpers as part of o-typography and guss-typography itself as a dependency https://github.com/Financial-Times/o-typography/commit/619ae7ef6d4a0557f9346819ddba50ec3568b294.

The demos are still OK, let me know if there are any issues.

**Comment by matthew-andrews** [comment]
:boom:

**Pull request merged**
